{% set name = "mgrs" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 123d0e1b0a052fc47e0f006f5403bd7f397947228297356e44b463db16a25dd5

build:
  number: 0
  skip: true  # [win and vc<14]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - wheel

test:
  imports:
    - mgrs

about:
  home: https://github.com/hobu/mgrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: MGRS coordinate conversion for Python
  dev_url: https://github.com/hobu/mgrs

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
